language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - FLOW_VERSION=3.2.*
  - FLOW_VERSION=3.1.*
  - FLOW_VERSION=3.0.*
  - FLOW_VERSION=dev-master

before_script:
  - env
  - mkdir Build; cd Build
  - VERSION=$( if [ $TRAVIS_TAG ] ; then echo $TRAVIS_TAG ; else echo "dev-${TRAVIS_BRANCH}#${TRAVIS_COMMIT}" ; fi )
  # Test this
  - |
    cat <<EOF > composer.json
    {
        "name": "typo3/flow-base-distribution",
        "config": {
            "vendor-dir": "Packages/Libraries",
            "bin-dir": "bin"
        },
        "require": {
            "flowpack/elasticsearch": "${VERSION}"
        },
        "require-dev": {
            "typo3/buildessentials": "~3.0",
            "mikey179/vfsstream": "~1.6",
            "phpunit/phpunit": "~4.8 || ~5.2.0"
        },
        "scripts": {
            "post-update-cmd": "TYPO3\\\\Flow\\\\Composer\\\\InstallerScripts::postUpdateAndInstall",
            "post-install-cmd": "TYPO3\\\\Flow\\\\Composer\\\\InstallerScripts::postUpdateAndInstall"
        }
    }
    EOF
  # Install Flow in different versions
  - composer require typo3/flow:${FLOW_VERSION} --no-update
  - composer update --dev
  # We need to override the default Routes because they reference the non-existing Welcome package
  - |
    cat <<EOF > Configuration/Routes.yaml
    -
      name: 'Flow'
      uriPattern: '<FlowSubroutes>'
      defaults:
        '@format': 'html'
      subRoutes:
        FlowSubroutes:
          package: TYPO3.Flow
    EOF
script: phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Flowpack.ElasticSearch/Tests/Functional